FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY target/webscraping-service-0.0.1-SNAPSHOT.jar webscraping-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/app/webscraping-service-0.0.1-SNAPSHOT.jar"]