
services:
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - oasis-net
    environment:
      - VITE_APP_USE_MOCK=false

  property-service:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - oasis-net
    depends_on:
      - property-mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATA_MONGODB_HOST=property-mongodb
      - SPRING_DATA_MONGODB_DATABASE=main

  property-mongodb:
    image: mongo:latest
    ports:
      - "4081:4081"
    volumes:
      - ./property-service/mongod.conf:/etc/mongod.conf
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    networks:
      - oasis-net

  mortgage-service:
    build:
      context: ./mortgage-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - oasis-net
    environment:
      - SPRING_PROFILES_ACTIVE=default

  applicant-service:
    build:
      context: ./applicant-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - oasis-net
    depends_on:
      - applicant-mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATA_MONGODB_HOST=applicant-mongodb
      - SPRING_DATA_MONGODB_DATABASE=main

  applicant-mongodb:
    image: mongo:latest
    ports:
      - "4083:4083"
    volumes:
      - ./applicant-service/mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
    networks:
      - oasis-net

networks:
  oasis-net:
    driver: bridge
