
services:
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - oasis-net

  property-service:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - oasis-net
    depends_on:
      - property-mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATA_MONGODB_HOST=property-mongodb
      - SPRING_DATA_MONGODB_DATABASE=main

  property-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - oasis-net

  mortgage-service:
    build:
      context: ./mortgage-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - oasis-net
    environment:
      - SPRING_PROFILES_ACTIVE=default

networks:
  oasis-net:
    driver: bridge
