FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY target/property-service-0.0.1-SNAPSHOT.jar property-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/app/property-service-0.0.1-SNAPSHOT.jar"]