FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY target/mortgage-service-0.0.1-SNAPSHOT.jar mortgage-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/app/mortgage-service-0.0.1-SNAPSHOT.jar"]