FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY target/applicant-service-0.0.1-SNAPSHOT.jar applicant-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/app/applicant-service-0.0.1-SNAPSHOT.jar"]